name: Update Branch

on:
  schedule:
    - cron: '0 4,16 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "i love git"
          git config user.email "<>"

      - name: Pull with Rebase
        run: git pull --rebase origin v2

      - name: Push Changes
        run: |
          git push -u origin v2 || echo "Push failed. Retrying..."
          while [ $? -ne 0 ]; do
            git pull --rebase origin v2
            git push -u origin v2
          done
