name: Telemetro (Panamá)

on:
  schedule:
    - cron: '0 */4 * * *'
  
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

       
      - name: get config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"
      
      - name: grab dailymotion stream
        run: |
          pwd
          cd ./core/platforms/
          python3 dailymotion.py x8nlwwo > ../../streams/Telemetro _Panama.m3u8
        
      - name: adding everything
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "Telemetro (Panamá) updated"
          git push
